# Fly.io configuration for EWCL API
app = "ewcl-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  # Production environment variables
  PYTHONUNBUFFERED = "1"
  PYTHONDONTWRITEBYTECODE = "1"
  
  # API configuration (no API key for public access)
  API_KEY = ""
  MAX_BODY_BYTES = "10485760"  # 10MB
  ALLOWED_ORIGINS = "*"
  
  # Model bundle paths
  EWCL_BUNDLE_DIR = "/app/backend_bundle"
  EWCLV1C_BUNDLE_DIR = "/app/backend_bundle"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048

[deploy]
  release_command = "echo 'Deploying EWCL API with models...'"
