services:
  - type: web
    name: ewcl-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:api --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
